name: ci

on:
  pull_request:
    branches: [ "main" ]
    # Optional: save CI minutes by skipping docs-only changes
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  push:
    branches: [ "main" ]  # so main is always green

# Cancel older in-flight runs for the same PR to free runners
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Rust ${{ matrix.toolchain }} • ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]           # add macos-latest, windows-latest if needed
        toolchain: ["stable"]         # add "beta" (or a pinned version) if you want
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}

      # Cache Cargo registry and target to speed up builds
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Optional: ensure reproducible env (e.g., required system libs)
      - name: Show rustc/cargo versions
        run: |
          rustc -Vv
          cargo -V

      - name: Build
        run: cargo build --locked --verbose

      - name: Test
        env:
          RUST_LOG: info
        run: cargo test --locked --all --verbose
